### ISSUE TITLE
Bounded grids appear to be ignored

### ISSUE THREAD

**Issue by muzikbike** [rei1024/oscilloscope#28]
This p4 wick:
x = 12, y = 9, rule = B3/S23:T12,11
2o2b2o2b2o$2o2b2o2b2o2$12o4$2b2o2b2o2b2o$2b2o2b2o2b2o!

causes an error implying its period exceeds 50000:
![Image](https://github.com/user-attachments/assets/dd658bd8-9ef4-4f0c-8fba-1cd4370faf7d)

I assume the bounded grid isn't being recognised and the pattern is being run on an infinite plane, causing the error.

Either bounded grids should be supported, or there should be an error saying they are not.

**Comment by rei1024** [comment]
Error message is fixed at #29

**Comment by rei1024** [comment]
Golly does not support it but LifeViewer does. fixed by #34

**Comment by muzikbike** [comment]
Size 0 is usually taken to represent infinity, and on both axes usually represents an unbounded grid (and as such the bounded grid extension is removed). However, we still get errors for the following:
x = 4, y = 4, rule = B3/S23:P0,0
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:T0,0
2bo$obo$bobo$bo!

**Comment by muzikbike** [comment]
There are also errors with the following:
x = 4, y = 4, rule = B3/S23:K0,0
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:K0,0*
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:K0*,0
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:C0,0
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:S0
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:S0*
2bo$obo$bobo$bo!

**Comment by muzikbike** [comment]
These also get the generic invalid rejection message rather than being recognised as bounded grids (in cases where only one value is specified, we consider the grid to be square):
x = 4, y = 4, rule = B3/S23:P10
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:T10
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:K10
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:K10*
2bo$obo$bobo$bo!
x = 4, y = 4, rule = B3/S23:C10
2bo$obo$bobo$bo!

**Comment by muzikbike** [comment]
related: https://conwaylife.com/forums/viewtopic.php?p=159004#p159004

**Comment by muzikbike** [comment]
can confirm that P0,0 and T0,0 now work (as do T0+n,0 and T0,0+n); the others still produce a generic error, which I assume is known since these haven't been implemented fully in the other project yet

**Comment by rei1024** [comment]
Fix #89 for cases like P20

**Comment by muzikbike** [comment]
so the only things needing attention now are C0,0 and such?
